# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20100921160120) do

  create_table "loanapps", :force => true do |t|
    t.string   "credit_type"
    t.string   "account_type"
    t.string   "amount_requested"
    t.string   "purpose_of_loan"
    t.string   "collateral_offered"
    t.string   "time_to_repay"
    t.string   "type_of_repay"
    t.string   "payment_protection_disability"
    t.string   "payment_protection_single"
    t.string   "payment_protection_joint"
    t.string   "applicant_citizenship"
    t.string   "applicant_name"
    t.string   "applicant_account_number"
    t.string   "applicant_ssn"
    t.string   "applicant_mother_maiden_name"
    t.string   "applicant_marital_status"
    t.string   "applicant_license_number"
    t.string   "applicant_license_state"
    t.string   "applicant_birth_date"
    t.string   "applicant_dependents_ages"
    t.string   "applicant_home_phone"
    t.string   "applicant_work_phone"
    t.string   "applicant_email_address"
    t.string   "applicant_address"
    t.string   "applicant_city"
    t.string   "applicant_state"
    t.integer  "applicant_zip"
    t.string   "years_in_present_address"
    t.string   "ownership_of_present_address"
    t.string   "applicant_previous_address"
    t.string   "applicant_previous_city"
    t.string   "applicant_previous_state"
    t.integer  "applicant_previous_zip"
    t.string   "years_in_previous_address"
    t.string   "ownership_of_previous_address"
    t.string   "applicant_employer"
    t.string   "applicant_employer_address"
    t.string   "applicant_employer_city"
    t.string   "applicant_employer_state"
    t.integer  "applicant_employer_zip"
    t.string   "applicant_employer_supervisor"
    t.string   "applicant_current_title"
    t.string   "applicant_employment_start_date"
    t.string   "hours_at_work"
    t.string   "type_of_business"
    t.string   "applicant_income"
    t.string   "applicant_income_type"
    t.string   "applicant_income_frequency"
    t.string   "applicant_other_income_source"
    t.string   "applicant_other_income"
    t.string   "applicant_other_income_frequency"
    t.string   "applicant_military_duty"
    t.string   "applicant_previous_employer"
    t.string   "applicant_previous_employer_address"
    t.string   "applicant_previous_employer_city"
    t.string   "applicant_previous_employer_state"
    t.integer  "applicant_previous_employer_zip"
    t.string   "applicant_previous_employment_startdate"
    t.string   "applicant_previous_employment_enddate"
    t.string   "applicant_reference_name"
    t.string   "applicant_reference_relationship"
    t.string   "applicant_reference_address"
    t.string   "applicant_reference_city"
    t.string   "applicant_reference_state"
    t.integer  "applicant_reference_zip"
    t.string   "applicant_reference_home_phone"
    t.string   "applicant_mortgage_rent"
    t.string   "applicant_creditor"
    t.string   "applicant_debt_interest_rate"
    t.string   "applicant_mortgage_present_balance"
    t.string   "applicant_mortgage_monthly_payment"
    t.string   "joint_applicant_citizenship"
    t.string   "joint_applicant_name"
    t.string   "joint_applicant_account_number"
    t.string   "joint_applicant_ssn"
    t.string   "joint_applicant_mother_maiden_name"
    t.string   "joint_applicant_marital_status"
    t.string   "joint_applicant_license_number"
    t.string   "joint_applicant_license_state"
    t.string   "joint_applicant_birth_date"
    t.string   "joint_applicant_dependents_ages"
    t.string   "joint_applicant_home_phone"
    t.string   "joint_applicant_work_phone"
    t.string   "joint_applicant_email_address"
    t.string   "joint_applicant_address"
    t.string   "joint_applicant_city"
    t.string   "joint_applicant_state"
    t.integer  "joint_applicant_zip"
    t.string   "years_in_present_address_for_joint"
    t.string   "ownership_of_present_address_for_joint"
    t.string   "joint_applicant_previous_address"
    t.string   "joint_applicant_previous_city"
    t.string   "joint_applicant_previous_state"
    t.integer  "joint_applicant_previous_zip"
    t.string   "years_in_previous_address_for_joint"
    t.string   "ownership_of_previous_address_for_joint"
    t.string   "joint_applicant_employer"
    t.string   "joint_applicant_employer_address"
    t.string   "joint_applicant_employer_city"
    t.string   "joint_applicant_employer_state"
    t.integer  "joint_applicant_employer_zip"
    t.string   "joint_applicant_employer_supervisor"
    t.string   "joint_applicant_current_title"
    t.string   "joint_applicant_employment_start_date"
    t.string   "hours_at_work_for_joint"
    t.string   "type_of_business_for_joint"
    t.string   "joint_applicant_income"
    t.string   "joint_applicant_income_type"
    t.string   "joint_applicant_income_frequency"
    t.string   "joint_applicant_other_income_source"
    t.string   "joint_applicant_other_income"
    t.string   "joint_applicant_other_income_frequency"
    t.string   "joint_applicant_military_duty"
    t.string   "joint_applicant_previous_employer"
    t.string   "joint_applicant_previous_employer_address"
    t.string   "joint_applicant_previous_employer_city"
    t.string   "joint_applicant_previous_employer_state"
    t.integer  "joint_applicant_previous_employer_zip"
    t.string   "joint_applicant_previous_employment_startdate"
    t.string   "joint_applicant_previous_employment_enddate"
    t.string   "joint_applicant_reference_name"
    t.string   "joint_applicant_reference_relationship"
    t.string   "joint_applicant_reference_address"
    t.string   "joint_applicant_reference_city"
    t.string   "joint_applicant_reference_state"
    t.integer  "joint_applicant_reference_zip"
    t.string   "joint_applicant_reference_home_phone"
    t.string   "joint_applicant_mortgage_rent"
    t.string   "joint_applicant_creditor"
    t.string   "joint_applicant_debt_interest_rate"
    t.string   "joint_applicant_mortgage_present_balance"
    t.string   "joint_applicant_mortgage_monthly_payment"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "memberapps", :force => true do |t|
    t.string   "name"
    t.string   "ssn"
    t.string   "salutation"
    t.string   "joint_name"
    t.string   "address"
    t.string   "city"
    t.string   "state"
    t.integer  "zip"
    t.string   "home_phone"
    t.string   "work_phone"
    t.string   "birth_date"
    t.string   "member_eligibility"
    t.string   "badge_no"
    t.string   "hire_date"
    t.string   "email_address"
    t.string   "time2call"
    t.string   "citizen"
    t.string   "account"
    t.string   "overdraft_protection"
    t.string   "typeof_protection"
    t.string   "atm_card"
    t.string   "mmdebit_card"
    t.string   "audio_response"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "rfis", :force => true do |t|
    t.string   "membership_application"
    t.string   "family_membership"
    t.string   "savings_account"
    t.string   "sharedraft_ac"
    t.string   "christmas_clubac"
    t.string   "money_marketac"
    t.string   "individual_retirement"
    t.string   "irashare_certificates"
    t.string   "share_certificates"
    t.string   "audio_response"
    t.string   "overdraft_loan"
    t.string   "personal_loan"
    t.string   "automobile_loan"
    t.string   "heloc"
    t.string   "mortgage_loan"
    t.string   "visa_creditcard"
    t.string   "mac_atmcard"
    t.string   "master_moneydc"
    t.string   "payroll_deduction"
    t.string   "direct_deposit"
    t.string   "money_orders"
    t.string   "travelers_check"
    t.string   "notary_service"
    t.string   "entertainment_tickets"
    t.string   "other_info"
    t.string   "other_questions"
    t.string   "name"
    t.string   "phone"
    t.string   "email"
    t.string   "address"
    t.string   "city"
    t.string   "state"
    t.integer  "zip"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
